# Generated by Django 5.1.1 on 2024-10-20 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Blog",
            new_name="Materials",
        ),
        migrations.AlterModelOptions(
            name="materials",
            options={
                "ordering": ["name"],
                "verbose_name": "Материал",
                "verbose_name_plural": "Материалы",
            },
        ),
    ]
