# Generated by Django 5.1.1 on 2024-10-29 11:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_rename_blog_materials_alter_materials_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materials",
            name="content",
            field=models.TextField(
                help_text="Введите содержимое", max_length=50, verbose_name="содержимое"
            ),
        ),
        migrations.AlterField(
            model_name="materials",
            name="date_create",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="materials",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Опубликовано"),
        ),
        migrations.AlterField(
            model_name="materials",
            name="slug",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="slug"
            ),
        ),
    ]
