# Generated by Django 5.1.1 on 2024-09-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите наименование категории",
                        max_length=50,
                        verbose_name="Наименование категории",
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание категории")),
            ],
            options={
                "verbose_name": "Категория",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите наименование продукта",
                        max_length=50,
                        verbose_name="Наименование продукта",
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание продукта")),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="product/photo"),
                ),
                (
                    "category",
                    models.CharField(max_length=100, verbose_name="Категория продукта"),
                ),
                ("price", models.IntegerField(verbose_name="Наименование продукта")),
                ("date_create", models.DateTimeField(verbose_name="Дата создания")),
                (
                    "date_change",
                    models.DateTimeField(verbose_name="Дата последнего изменения"),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "ordering": ["name", "category"],
            },
        ),
    ]
