# Generated by Django 5.1.1 on 2024-11-13 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_category_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_number",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Введите номер версии продукта",
                        verbose_name="Номер версии продукта",
                    ),
                ),
                (
                    "version_name",
                    models.CharField(
                        help_text="Введите наименование версии продукта",
                        max_length=50,
                        verbose_name="Наименование версии продукта",
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=True,
                        help_text="Версия активна?",
                        verbose_name="признак текущей версии",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="version",
                        to="catalog.product",
                        verbose_name="Наименование продукта",
                    ),
                ),
            ],
        ),
    ]
